### ISSUE TITLE
ProblemStatement Review

### ISSUE THREAD

**Issue by kypss94132** [kypss94132/CAS741_YiLeng-Chen#1]
Dear Dr. Smith,
I have already uploaded the problem statement files. Kindly review them at your convenience. Thank you.

**Comment by smiths** [comment]
Feedback:

- please provide a link to [your document](https://github.com/kypss94132/CAS741_YiLeng-Chen/blob/main/docs/ProblemStatementAndGoals/ProblemStatement.pdf) in your issue

We've already discussed your project over e-mail.  I like that you've made the changes I suggested.

Your project is approved.  I look forward to seeing what you create this term.  :smile:
