### ISSUE TITLE
Explain symbol when first appear

### ISSUE THREAD

**Issue by CynthiaLiu0805** [kypss94132/CAS741_YiLeng-Chen#13]
It could be time-consuming when seeing a symbol for the first time and not knowing what it means and needing to go back to refer to the symbol table, such as in 4.2.1 what is $k_d$ in A1, M1/M2 in A6. Maybe use wording language rather than symbols?

**Comment by kypss94132** [comment]
Instead of using symbols that may cause confusion, attempt to describe certain parts using words or simplify the symbols for better understanding. (Changes implemented in commit [#27561aa](https://github.com/kypss94132/CAS741_YiLeng-Chen/commit/27561aa40bd468bc058d22af8cff62e1abfb9e15).)
