### ISSUE TITLE
Rationale

### ISSUE THREAD

**Issue by CynthiaLiu0805** [kypss94132/CAS741_YiLeng-Chen#14]
Can you provide some rationale for assumptions and likely changes to support your decisions?

**Comment by kypss94132** [comment]
Update assumptions, likely changes, and unlikely changes through commit [f42ab67.](https://github.com/kypss94132/CAS741_YiLeng-Chen/commit/f42ab67d1fdfdbc5d5c876fed02cf72c5b87404a)
