### ISSUE TITLE
Clarification of input

### ISSUE THREAD

**Issue by CynthiaLiu0805** [kypss94132/CAS741_YiLeng-Chen#15]
It's a bit confusing regarding what the inputs are, could you provide the units for each symbol input, or perhaps specifying their types?

**Comment by kypss94132** [comment]
Clarify the input and output equations and units through commit [8e2008f](https://github.com/kypss94132/CAS741_YiLeng-Chen/commit/8e2008facd47c502f49eb6a9d08a129e1967cc48).
