### ISSUE TITLE
Clarification of models

### ISSUE THREAD

**Issue by CynthiaLiu0805** [kypss94132/CAS741_YiLeng-Chen#16]
Maybe because of the $Ref. By$ link is broken, it is unclear how the output field in IM is generated. Are they from the DD? Or are there any other model that is not included.

**Comment by kypss94132** [comment]
Fix and clarify the referenced parts in the DDs and IMs through commit [8e2008f ](https://github.com/kypss94132/CAS741_YiLeng-Chen/commit/8e2008facd47c502f49eb6a9d08a129e1967cc48)to illustrate the relationship between DDs and IMs.
