### ISSUE TITLE
VnVPlan Review

### ISSUE THREAD

**Issue by kypss94132** [kypss94132/CAS741_YiLeng-Chen#17]
Dear Dr. Smith,

My VnVPlan document is ready and the link is provided[ here.](https://github.com/kypss94132/CAS741_YiLeng-Chen/blob/main/docs/VnVPlan/VnVPlan.pdf)
I am looking forward to receiving some feedback. Thank you!

**Comment by smiths** [comment]
[YiLeng_VnVPlan.pdf](https://github.com/kypss94132/CAS741_YiLeng-Chen/files/14566809/YiLeng_VnVPlan.pdf)
