### ISSUE TITLE
VnVPlan Review(Secondary)

### ISSUE THREAD

**Issue by kypss94132** [kypss94132/CAS741_YiLeng-Chen#19]
Hi Waqar,

My VnVPlan document is provided [here](https://github.com/kypss94132/CAS741_YiLeng-Chen/blob/main/docs/VnVPlan/VnVPlan.pdf).
I am looking forward to receiving some feedback. Thank you!

**Comment by WaqarAwan376** [comment]
I have reviewed your VnV plan and mentioned the areas where you can improve according to my knowledge.
