### ISSUE TITLE
VnV Review: Dynamic Testing

### ISSUE THREAD

**Issue by WaqarAwan376** [kypss94132/CAS741_YiLeng-Chen#25]
In section 3.5, Please state how dynamic testing will be employed to validate code quality and specifications, including the tools and methodologies to be used.

**Comment by kypss94132** [comment]
Flake8 will be used to validate code quality, which is clarified through commit [4d19e71.](https://github.com/kypss94132/CAS741_YiLeng-Chen/commit/4d19e719c9cb442c986ec428a2d8b739ce6f6034)
