### ISSUE TITLE
VnV Review: CI Testing

### ISSUE THREAD

**Issue by WaqarAwan376** [kypss94132/CAS741_YiLeng-Chen#26]
In section 3.6, Would be nice if you specify what kind of tests are you going to conduct in your GitHub actions.

**Comment by kypss94132** [comment]
The details about GitHub Actions are clarified through commit [4d19e71.](https://github.com/kypss94132/CAS741_YiLeng-Chen/commit/4d19e719c9cb442c986ec428a2d8b739ce6f6034)
