### ISSUE TITLE
VnV Review: Static Code Analysis

### ISSUE THREAD

**Issue by WaqarAwan376** [kypss94132/CAS741_YiLeng-Chen#27]
In section 3.6, It would be nice if you included static code analysis tools like Flake8 that can serve as the primary linter, ensuring code quality and adherence to Python coding standards.

**Comment by kypss94132** [comment]
Flake8 was added to the document through commit [#18b1d07](https://github.com/kypss94132/CAS741_YiLeng-Chen/commit/18b1d07c61d872145c6de7e6a0a309ed70ebdceb)
