### ISSUE TITLE
VnV Review: NFR Testing

### ISSUE THREAD

**Issue by WaqarAwan376** [kypss94132/CAS741_YiLeng-Chen#28]
In section 4.2, The plan for nonfunctional requirements testing, including usability tests, appears limited to me. I think that critical nonfunctional requirements like performance, security, and compatibility testing would provide a more comprehensive understanding of the system's working.

**Comment by kypss94132** [comment]
Thank you for the advice. Regarding the security aspect, it might be outside the scope of this project, as there is little opportunity to handle confidential data inputs. Even the weather data used in the program is open data provided by the government.
