### ISSUE TITLE
SRS Review

### ISSUE THREAD

**Issue by kypss94132** [kypss94132/CAS741_YiLeng-Chen#3]
Dear Dr. Smith,

My SRS document is ready and the link is provided [here](https://github.com/kypss94132/CAS741_YiLeng-Chen/blob/main/docs/SRS/SRS.pdf).
I am looking forward to receiving some feedback. Thank you!

**Comment by smiths** [comment]
[Yi-LengChen_SRS.pdf](https://github.com/kypss94132/CAS741_YiLeng-Chen/files/14390896/Yi-LengChen_SRS.pdf)

The feedback is attached.  You may wish to create issues from the feedback to organize your work and clearly show the changes between the current version and the final version.  The grade will be posted on Avenue soon.
