### ISSUE TITLE
MG & MIS Review

### ISSUE THREAD

**Issue by kypss94132** [kypss94132/CAS741_YiLeng-Chen#31]
Dear Dr. Smith,

My [MG](https://github.com/kypss94132/CAS741_YiLeng-Chen/blob/main/docs/Design/SoftArchitecture/MG.pdf) & [MIS](https://github.com/kypss94132/CAS741_YiLeng-Chen/blob/main/docs/Design/SoftDetailedDes/MIS.pdf) documents are ready.
I am looking forward to receiving some feedback. Thank you!

**Comment by smiths** [comment]
[Yi-LengMG.pdf - PDF Expert.pdf](https://github.com/kypss94132/CAS741_YiLeng-Chen/files/14846246/Yi-LengMG.pdf.-.PDF.Expert.pdf)
[Yi-LengMIS.pdf - PDF Expert.pdf](https://github.com/kypss94132/CAS741_YiLeng-Chen/files/14846248/Yi-LengMIS.pdf.-.PDF.Expert.pdf)
