### ISSUE TITLE
MIS Review- 7-4-4

### ISSUE THREAD

**Issue by AtiyehSayadi** [kypss94132/CAS741_YiLeng-Chen#33]
In this module you did not define any input for your access program, but in this part you write sth about input format. what is the input?

**Comment by kypss94132** [comment]
Redefine sections 6 to 9 to clarify the inputs for each module, as specified in commit [3e94cab.](https://github.com/kypss94132/CAS741_YiLeng-Chen/commit/3e94cab0799f4b75714784217638e9e5acd63325)
