### ISSUE TITLE
MG & MIS Review(Secondary Expert)

### ISSUE THREAD

**Issue by kypss94132** [kypss94132/CAS741_YiLeng-Chen#38]
Hi Kim Ying,

My [MG](https://github.com/kypss94132/CAS741_YiLeng-Chen/blob/main/docs/Design/SoftArchitecture/MG.pdf) & [MIS](https://github.com/kypss94132/CAS741_YiLeng-Chen/blob/main/docs/Design/SoftDetailedDes/MIS.pdf) documents are ready.
I am looking forward to receiving some feedback. Thank you!

**Comment by gordonwky** [comment]
My review is Here
[MIS-Yi-Leng.pdf](https://github.com/kypss94132/CAS741_YiLeng-Chen/files/14680712/MIS-Yi-Leng.pdf)
[MG-Yi-Leng.pdf](https://github.com/kypss94132/CAS741_YiLeng-Chen/files/14680713/MG-Yi-Leng.pdf)

**Comment by kypss94132** [comment]
MG file:
Take the suggestions to clarify ACs in section 4.1 and the AC table in section 8 through commit [afdb4a7.](https://github.com/kypss94132/CAS741_YiLeng-Chen/commit/afdb4a79cfa2889bd0fe15835bf98559aa5b39e8)
