### ISSUE TITLE
SRS Review(Domain Expert)

### ISSUE THREAD

**Issue by kypss94132** [kypss94132/CAS741_YiLeng-Chen#4]
Hi Atiyeh,

My SRS document is provided [here](https://github.com/kypss94132/CAS741_YiLeng-Chen/blob/main/docs/SRS/SRS.pdf).
I am looking forward to receiving some feedback. Thank you!

**Comment by AtiyehSayadi** [comment]
Hello,
Thank you very much for inviting me to review this document. Your document was well-written, and I'll share separately with you the specific points that were ambiguous and needed further clarification.
Atiyeh

**Comment by AtiyehSayadi** [comment]
"The 'Table of Units' is better arranged alphabetically."

**Comment by AtiyehSayadi** [comment]
In section 3.1, What are the valid characteristics of input  to be verified by user?

**Comment by AtiyehSayadi** [comment]
In section 4.1.1 and for item 2, it would be better to provide a concise definition for each item. It's advisable to use citations for a more formal definition of each term.

**Comment by AtiyehSayadi** [comment]
hen using time units for DD3 and DD4, you can use second(S) as SI.

**Comment by AtiyehSayadi** [comment]
For IMs, it's better to explain how inputs lead to outputs through mathematical equations.

**Comment by AtiyehSayadi** [comment]
It seems like  your "Table of Traceability" should have more connections because you had DDs that, for example, were not used in any of the IMs. If there was no necessity for their use, why were they defined, and if there was a need, why were they never referenced?
