### ISSUE TITLE
SRS Review(Secondary)

### ISSUE THREAD

**Issue by kypss94132** [kypss94132/CAS741_YiLeng-Chen#5]
Hi Cynthia,

My SRS document is provided [here](https://github.com/kypss94132/CAS741_YiLeng-Chen/blob/main/docs/SRS/SRS.pdf).
I am looking forward to receiving some feedback. Thank you!

**Comment by CynthiaLiu0805** [comment]
Hi Yi-Leng,
Sorry for the late reply, the issues are created as #12 #13 #14 #15 #16.
Cynthia
